POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"thehieu",
    "password":"1"
}


###
GET  http://localhost:5000/api/auth/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjg5NDk4MmFiY2YyNmYzNzRjYWI0ZWQiLCJ1c2VybmFtZSI6InRoZWhpZXUiLCJpYXQiOjE2NjM4NDMyNzUsImV4cCI6MTY2Mzg0MzU3NX0.zdsVSHsWH5GsUExqkNj7LPP7lpceFgnnqpoI2Q2z2Ss
