POST https://mern-learnit-server1.herokuapp.com/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"thehieu",
    "password":"1"
}


###
GET  http://localhost:8080/api/auth/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjY5NjEwMzQ5fQ.fgBMp7c_giaE99cdRexLtsiUxk2iQeQVkOoH6gWVLzk
###login
post  http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "00000000"
}
###
get http://localhost:8080/api/categories/
###
post  http://localhost:8080/api/categories/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjY3Mjg0NzM2fQ.3ucpSdzkt0rokVPMGgXSSa31YGeKTOp05SF01ToNm-I
Content-Type: application/json

{
    "cateName": "rice2",
    "image": "string"
}
###
put  http://localhost:8080/api/categories/8 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjcwNDI3OTA5fQ.ZxegjQdP9GoWm0vCS3Qd9NmJDRoBD4LpsmVrRI8MoU0
Content-Type: application/json

{
    "cateName": "mi tom",
    "description": "ngon",
    "image": "stringaaa 111"
}

### categories
get  http://localhost:8080/api/products/ HTTP/1.1
### product
put  http://localhost:8080/api/products/98 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjcyMDc1NDM2fQ.qO0zNiIzVdlrTiGXnofqmXXvywtIksBmdPG9ikyR2AU
Content-Type: application/json

{
  "productName": "food5",
  "description": "Trong ẩm thực Việt, có lẽ chẳng món ăn nào “dễ chịu” như gỏi cuốn. Dùng làm thức ăn nhẹ cũng được, mà ăn no căng bụng cũng không ngấy;",
  "categoryIds": [5,8],
  "price": 200,
   "amount": 0,
  "imageDtos": [
    {
      "imageURL": "http://res.cloudinary.com/dk2peasgq/image/upload/v1669101541/qjwmh2e1piwuzvx6gavq.jpg"
    },
    {
      "imageURL": "http://res.cloudinary.com/dk2peasgq/image/upload/v1669101541/qjwmh2e1piwuzvx6gavq.jpg"
    }
  ]
}
###
post  http://localhost:8080/api/products HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjY5MTM3NDQ3fQ.7yhFBqeXyryvIBDL9y01HonubdZqAWQ2TAJFOYbuZ10
Content-Type: application/json

{
  "productName": "com chien111",
  "description": "Trong ẩm thực Việt, có lẽ chẳng món ăn nào “dễ chịu” như gỏi cuốn. Dùng làm thức ăn nhẹ cũng được, mà ăn no căng bụng cũng không ngấy;",
  "categoryIds": [5,8],
  "price": 20,
   "amount": 0,
  "imageDtos": [
    {
      "imageURL": "http://res.cloudinary.com/dk2peasgq/image/upload/v1669101541/qjwmh2e1piwuzvx6gavq.jpg"
    }
  ]
}

###
get http://localhost:8080/api/products?page=0&size=8&name=222" HTTP/1.1
###?page=1&pageSize=3
post http://localhost:8080/api/orders HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjY3ODkwNDg3fQ.HbJkQ_EJINKu54CuKNVCl9Yyt2iYvgBZGi77mpn6r50
Content-Type: application/json

{
  "customerId": 3,
  "orderDetails": [
    {
      "productId": 6,
      "amount": 3
    },
    {
      "productId": 9,
      "amount": 2
    }
  ]
}
###
put  http://localhost:8080/api/products/24 HTTP/1.1
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjY3NzE0ODgwfQ.UJ_Qdx3WnHagCctHCSAnoDO6Bg0kBQIGO5NWgXFYpkU
Content-Type: application/json

{
  "productName": "mi tom hao hao",
  "description": "ngon qua troi",
  "categoryIds": [
    5
  ],
  "price": 22,
  "status": "DELETED",
    "imageDtos": [
    {
      "imageURL": "string"
    }
  ]
}

###

PATCH http://localhost:8080/api/orders/33 HTTP/1.1
Authorization: Basic eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjY4MDY4Nzc5fQ.Hx0la_-zYJXl-F8ax31JOHPZSQbakitTP2aYh7lhMKU
Content-Type: application/json

{
  "orderStatus" :"ORDERED"
}


###
api update carts

{
  customerId,
  carts: [{
    productId,
    amount,
  }]
}
###

post http://localhost:8080/api/carts
Content-Type: application/json

{
  "customerId":3,
  "productId":17,
  "amount":2
}

###
get http://localhost:8080/api/products?price=0&page=0&rating=0&priceOn=1000000&size=10
