version: '2'

services:
  webfoodclient:
    image: webclient
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  webfoodserver:
    image: webfoodserverchat
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000


